language: r
cache: packages
warnings_are_errors: false

before_install:
  - tlmgr install ucs

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/bandit.R", "src/init.cpp"))'
